apiVersion: v1
kind: Pod
metadata:
  name: mycache
  labels:
    type: nginx
    app: mycache
spec:
  containers: 
    - name: nginx
      image: nginx
      resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
      ports:
        - containerPort: 6379
      env:
      - name: APP_COLOR
        value: "Blue"  
      envFrom:
      - configMapRef:
          name: myappconfig
      - secretRef:
          name: mysecret
      volumeMounts:
      - mountPath: "/data"
        name: myvol
  nodeSelector:
    type: nginx
    size: Large
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: mypvc
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - Large
            - Medium
  tolerations:
  - key: "size"
    operator: "Equal"
    value: "Small"
    effect: "NoSchedule"
      