apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    name: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-containers
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
  replicas: 3
