apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    name: mycache
    type: nginx
spec:
  template:
    metadata:
      name: mycache
      labels:
        type: nginx
        app: mycache
    spec:
      containers: 
          - name: nginx-containers
            image: nginx
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
  replicas: 3
